USE exam_control_db;

INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_option, marks, difficulty, subject, created_by) VALUES

-- MATHEMATICS (20 questions)
('What is the value of π (pi) up to two decimal places?', '3.14', '3.41', '3.12', '3.16', 'A', 1, 'EASY', 'Mathematics', 1),
('What is the square root of 144?', '11', '12', '13', '14', 'B', 1, 'EASY', 'Mathematics', 1),
('If a triangle has angles 60°, 60°, and 60°, what type of triangle is it?', 'Isosceles', 'Scalene', 'Equilateral', 'Right-angled', 'C', 1, 'EASY', 'Mathematics', 1),
('What is 15% of 200?', '25', '30', '35', '40', 'B', 1, 'EASY', 'Mathematics', 1),
('Solve: 2x + 5 = 15. What is x?', '4', '5', '6', '7', 'B', 1, 'EASY', 'Mathematics', 1),
('What is the area of a circle with radius 7 cm? (Use π = 22/7)', '144 cm²', '154 cm²', '164 cm²', '174 cm²', 'B', 2, 'MEDIUM', 'Mathematics', 1),
('What is the LCM of 12 and 18?', '24', '30', '36', '48', 'C', 1, 'EASY', 'Mathematics', 1),
('What is the HCF of 24 and 36?', '6', '8', '12', '18', 'C', 1, 'EASY', 'Mathematics', 1),
('A train travels 360 km in 4 hours. What is its speed?', '80 km/h', '90 km/h', '100 km/h', '110 km/h', 'B', 1, 'EASY', 'Mathematics', 1),
('What is 2^10?', '512', '1024', '2048', '256', 'B', 2, 'MEDIUM', 'Mathematics', 1),
('The sum of first 10 natural numbers is?', '45', '50', '55', '60', 'C', 1, 'EASY', 'Mathematics', 1),
('What is the slope of the line y = 3x + 5?', '5', '3', '8', '15', 'B', 2, 'MEDIUM', 'Mathematics', 1),
('What is the determinant of matrix [[1,2],[3,4]]?', '-2', '2', '-4', '4', 'A', 2, 'MEDIUM', 'Mathematics', 1),
('How many sides does a hexagon have?', '5', '6', '7', '8', 'B', 1, 'EASY', 'Mathematics', 1),
('What is the value of log₁₀(1000)?', '2', '3', '4', '10', 'B', 2, 'MEDIUM', 'Mathematics', 1),
('What is 0! (zero factorial)?', '0', '1', 'Undefined', 'Infinity', 'B', 1, 'EASY', 'Mathematics', 1),
('If P(A) = 0.4 and P(B) = 0.5 and they are independent, what is P(A∩B)?', '0.2', '0.4', '0.5', '0.9', 'A', 2, 'MEDIUM', 'Mathematics', 1),
('What is the derivative of x²?', 'x', '2x', '2', 'x²', 'B', 2, 'MEDIUM', 'Mathematics', 1),
('Solve: x² - 5x + 6 = 0. What are the roots?', '2 and 3', '1 and 6', '2 and 4', '3 and 4', 'A', 2, 'HARD', 'Mathematics', 1),
('What is the perimeter of a rectangle with length 10 cm and width 5 cm?', '25 cm', '30 cm', '50 cm', '15 cm', 'B', 1, 'EASY', 'Mathematics', 1),

-- PHYSICS (20 questions)
('What is the SI unit of force?', 'Watt', 'Joule', 'Newton', 'Pascal', 'C', 1, 'EASY', 'Physics', 1),
('What is the speed of light in vacuum?', '3 × 10⁶ m/s', '3 × 10⁸ m/s', '3 × 10¹⁰ m/s', '3 × 10⁴ m/s', 'B', 1, 'EASY', 'Physics', 1),
('Which law states that every action has an equal and opposite reaction?', 'Newton\'s First Law', 'Newton\'s Second Law', 'Newton\'s Third Law', 'Law of Gravitation', 'C', 1, 'EASY', 'Physics', 1),
('What is the unit of electrical resistance?', 'Ampere', 'Volt', 'Ohm', 'Watt', 'C', 1, 'EASY', 'Physics', 1),
('What is the formula for kinetic energy?', 'mgh', '½mv²', 'mv', 'F×d', 'B', 1, 'EASY', 'Physics', 1),
('Which type of wave does not require a medium to travel?', 'Sound waves', 'Water waves', 'Electromagnetic waves', 'Seismic waves', 'C', 1, 'EASY', 'Physics', 1),
('What is the SI unit of power?', 'Joule', 'Newton', 'Watt', 'Pascal', 'C', 1, 'EASY', 'Physics', 1),
('What happens to resistance when temperature increases in a conductor?', 'Decreases', 'Increases', 'Stays the same', 'Becomes zero', 'B', 2, 'MEDIUM', 'Physics', 1),
('What is the frequency of AC supply in India?', '50 Hz', '60 Hz', '100 Hz', '25 Hz', 'A', 1, 'EASY', 'Physics', 1),
('Which mirror is used in car headlights?', 'Concave mirror', 'Convex mirror', 'Plane mirror', 'Parabolic mirror', 'A', 2, 'MEDIUM', 'Physics', 1),
('What is the gravitational acceleration on Earth?', '8.9 m/s²', '9.8 m/s²', '10.8 m/s²', '9.0 m/s²', 'B', 1, 'EASY', 'Physics', 1),
('Ohm\'s Law states that V =?', 'I/R', 'IR', 'I+R', 'I-R', 'B', 1, 'EASY', 'Physics', 1),
('What is the unit of electric current?', 'Volt', 'Watt', 'Ampere', 'Ohm', 'C', 1, 'EASY', 'Physics', 1),
('Which phenomenon causes a stick to appear bent in water?', 'Reflection', 'Refraction', 'Diffraction', 'Dispersion', 'B', 1, 'EASY', 'Physics', 1),
('What is the half-life of a radioactive substance?', 'Time to double its mass', 'Time for half the atoms to decay', 'Time to fully decay', 'Time to emit half energy', 'B', 2, 'MEDIUM', 'Physics', 1),
('What type of lens is used to correct myopia?', 'Convex', 'Concave', 'Bifocal', 'Cylindrical', 'B', 1, 'EASY', 'Physics', 1),
('What is the SI unit of temperature?', 'Celsius', 'Fahrenheit', 'Kelvin', 'Rankine', 'C', 1, 'EASY', 'Physics', 1),
('Which law relates pressure and volume of a gas at constant temperature?', 'Charles\'s Law', 'Boyle\'s Law', 'Avogadro\'s Law', 'Gay-Lussac\'s Law', 'B', 2, 'MEDIUM', 'Physics', 1),
('What is the work done when force is perpendicular to displacement?', 'Maximum', 'Minimum', 'Zero', 'Negative', 'C', 2, 'MEDIUM', 'Physics', 1),
('What is the phenomenon of splitting of white light into its components called?', 'Reflection', 'Refraction', 'Dispersion', 'Diffraction', 'C', 1, 'EASY', 'Physics', 1),

-- CHEMISTRY (20 questions)
('What is the chemical formula of water?', 'H₂O₂', 'HO', 'H₂O', 'H₃O', 'C', 1, 'EASY', 'Chemistry', 1),
('What is the atomic number of Carbon?', '4', '6', '8', '12', 'B', 1, 'EASY', 'Chemistry', 1),
('Which gas is produced when acid reacts with metal?', 'Oxygen', 'Carbon dioxide', 'Hydrogen', 'Nitrogen', 'C', 1, 'EASY', 'Chemistry', 1),
('What is the pH of pure water?', '0', '7', '14', '5', 'B', 1, 'EASY', 'Chemistry', 1),
('What is the chemical symbol for Gold?', 'Go', 'Gd', 'Au', 'Ag', 'C', 1, 'EASY', 'Chemistry', 1),
('Which element has the highest electronegativity?', 'Oxygen', 'Chlorine', 'Fluorine', 'Nitrogen', 'C', 2, 'MEDIUM', 'Chemistry', 1),
('What is the valency of Oxygen?', '1', '2', '3', '4', 'B', 1, 'EASY', 'Chemistry', 1),
('Which is the most abundant gas in the atmosphere?', 'Oxygen', 'Carbon dioxide', 'Nitrogen', 'Argon', 'C', 1, 'EASY', 'Chemistry', 1),
('What type of bond is present in NaCl?', 'Covalent bond', 'Ionic bond', 'Metallic bond', 'Hydrogen bond', 'B', 1, 'EASY', 'Chemistry', 1),
('What is the molecular formula of glucose?', 'C₆H₁₂O₆', 'C₁₂H₂₂O₁₁', 'C₆H₁₂O₅', 'C₆H₆O₆', 'A', 2, 'MEDIUM', 'Chemistry', 1),
('Which acid is present in vinegar?', 'Hydrochloric acid', 'Sulfuric acid', 'Acetic acid', 'Nitric acid', 'C', 1, 'EASY', 'Chemistry', 1),
('What is the chemical name of baking soda?', 'Sodium chloride', 'Sodium carbonate', 'Sodium bicarbonate', 'Sodium hydroxide', 'C', 1, 'EASY', 'Chemistry', 1),
('How many electrons can the first shell of an atom hold?', '2', '4', '8', '18', 'A', 1, 'EASY', 'Chemistry', 1),
('What is the process of converting solid directly to gas called?', 'Evaporation', 'Condensation', 'Sublimation', 'Deposition', 'C', 2, 'MEDIUM', 'Chemistry', 1),
('Which gas causes the greenhouse effect most significantly?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 'C', 1, 'EASY', 'Chemistry', 1),
('What is the symbol of Iron?', 'Ir', 'In', 'Fe', 'Fr', 'C', 1, 'EASY', 'Chemistry', 1),
('Which law states that matter cannot be created or destroyed?', 'Law of Conservation of Energy', 'Law of Conservation of Mass', 'Boyle\'s Law', 'Dalton\'s Law', 'B', 2, 'MEDIUM', 'Chemistry', 1),
('What is an isotope?', 'Atoms with same mass but different atomic number', 'Atoms with same atomic number but different mass number', 'Atoms with same number of neutrons', 'Atoms with different electron count', 'B', 2, 'MEDIUM', 'Chemistry', 1),
('Which indicator turns red in acid and blue in base?', 'Phenolphthalein', 'Litmus', 'Methyl orange', 'Universal indicator', 'B', 1, 'EASY', 'Chemistry', 1),
('What is the chemical formula of table salt?', 'KCl', 'NaCl', 'CaCl₂', 'MgCl₂', 'B', 1, 'EASY', 'Chemistry', 1),

-- COMPUTER SCIENCE (20 questions)
('What does CPU stand for?', 'Central Processing Unit', 'Computer Processing Unit', 'Central Program Unit', 'Core Processing Unit', 'A', 1, 'EASY', 'Computer Science', 1),
('Which of the following is an input device?', 'Monitor', 'Printer', 'Keyboard', 'Speaker', 'C', 1, 'EASY', 'Computer Science', 1),
('What does HTML stand for?', 'Hyper Text Markup Language', 'High Text Markup Language', 'Hyper Transfer Markup Language', 'Hyper Text Making Language', 'A', 1, 'EASY', 'Computer Science', 1),
('Which data structure follows LIFO order?', 'Queue', 'Stack', 'Array', 'Tree', 'B', 1, 'EASY', 'Computer Science', 1),
('What is the binary representation of decimal 10?', '1010', '1100', '1001', '1110', 'A', 1, 'EASY', 'Computer Science', 1),
('What does OOP stand for?', 'Object Oriented Programming', 'Object Oriented Process', 'Ordered Object Programming', 'Object Operational Programming', 'A', 1, 'EASY', 'Computer Science', 1),
('Which language is primarily used for web styling?', 'HTML', 'JavaScript', 'CSS', 'PHP', 'C', 1, 'EASY', 'Computer Science', 1),
('What is the time complexity of binary search?', 'O(n)', 'O(n²)', 'O(log n)', 'O(1)', 'C', 2, 'MEDIUM', 'Computer Science', 1),
('Which of the following is NOT an OOP concept?', 'Inheritance', 'Polymorphism', 'Compilation', 'Encapsulation', 'C', 2, 'MEDIUM', 'Computer Science', 1),
('What does SQL stand for?', 'Structured Query Language', 'Simple Query Language', 'Sequential Query Language', 'Standard Query Language', 'A', 1, 'EASY', 'Computer Science', 1),
('Which protocol is used to browse the internet?', 'FTP', 'SMTP', 'HTTP', 'TCP', 'C', 1, 'EASY', 'Computer Science', 1),
('What is the full form of RAM?', 'Random Access Memory', 'Read Access Memory', 'Rapid Access Memory', 'Random Allocated Memory', 'A', 1, 'EASY', 'Computer Science', 1),
('Which sorting algorithm has best average-case time complexity?', 'Bubble Sort', 'Selection Sort', 'Quick Sort', 'Insertion Sort', 'C', 2, 'MEDIUM', 'Computer Science', 1),
('What is an IP address?', 'A software program', 'A unique identifier for a device on a network', 'A type of virus', 'A web browser', 'B', 1, 'EASY', 'Computer Science', 1),
('What does DNS stand for?', 'Domain Name System', 'Digital Network Service', 'Data Name System', 'Domain Network Server', 'A', 1, 'EASY', 'Computer Science', 1),
('Which gate outputs 1 only when all inputs are 1?', 'OR gate', 'NOT gate', 'AND gate', 'XOR gate', 'C', 1, 'EASY', 'Computer Science', 1),
('What is a compiler?', 'A program that translates high-level code to machine code', 'A type of hardware', 'A storage device', 'A network device', 'A', 1, 'EASY', 'Computer Science', 1),
('What is the primary key in a database?', 'A key that can have duplicate values', 'A key that uniquely identifies each record', 'A foreign key reference', 'An index key', 'B', 2, 'MEDIUM', 'Computer Science', 1),
('Which of the following is a non-relational database?', 'MySQL', 'PostgreSQL', 'MongoDB', 'Oracle', 'C', 2, 'MEDIUM', 'Computer Science', 1),
('What does HTTP status code 404 mean?', 'Server Error', 'Unauthorized', 'Not Found', 'Forbidden', 'C', 1, 'EASY', 'Computer Science', 1),

-- GENERAL KNOWLEDGE (20 questions)
('Who is known as the Father of the Nation in India?', 'Jawaharlal Nehru', 'Mahatma Gandhi', 'Subhas Chandra Bose', 'Bhagat Singh', 'B', 1, 'EASY', 'General Knowledge', 1),
('What is the capital of India?', 'Mumbai', 'Kolkata', 'New Delhi', 'Chennai', 'C', 1, 'EASY', 'General Knowledge', 1),
('How many planets are in our Solar System?', '7', '8', '9', '10', 'B', 1, 'EASY', 'General Knowledge', 1),
('Which is the largest ocean in the world?', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 'D', 1, 'EASY', 'General Knowledge', 1),
('Who wrote the national anthem of India?', 'Bankim Chandra Chatterjee', 'Rabindranath Tagore', 'Mahatma Gandhi', 'Sarojini Naidu', 'B', 1, 'EASY', 'General Knowledge', 1),
('What is the currency of Japan?', 'Yuan', 'Won', 'Yen', 'Ringgit', 'C', 1, 'EASY', 'General Knowledge', 1),
('Which is the longest river in the world?', 'Amazon', 'Nile', 'Ganges', 'Yangtze', 'B', 1, 'EASY', 'General Knowledge', 1),
('Who invented the telephone?', 'Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi', 'C', 1, 'EASY', 'General Knowledge', 1),
('What is the chemical symbol of water?', 'WA', 'W', 'H₂O', 'HO', 'C', 1, 'EASY', 'General Knowledge', 1),
('Which country is known as the Land of the Rising Sun?', 'China', 'South Korea', 'Japan', 'Thailand', 'C', 1, 'EASY', 'General Knowledge', 1),
('How many bones are in the adult human body?', '196', '206', '216', '226', 'B', 1, 'EASY', 'General Knowledge', 1),
('What is the full form of UNO?', 'United Nations Organisation', 'Universal Nations Organisation', 'United Nations Office', 'Unified Nations Organisation', 'A', 1, 'EASY', 'General Knowledge', 1),
('Which planet is known as the Red Planet?', 'Venus', 'Jupiter', 'Mars', 'Saturn', 'C', 1, 'EASY', 'General Knowledge', 1),
('Who was the first person to walk on the Moon?', 'Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn', 'C', 1, 'EASY', 'General Knowledge', 1),
('What is the smallest country in the world?', 'Monaco', 'San Marino', 'Vatican City', 'Liechtenstein', 'C', 1, 'EASY', 'General Knowledge', 1),
('Which gas do plants absorb during photosynthesis?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen', 'C', 1, 'EASY', 'General Knowledge', 1),
('Who invented the World Wide Web?', 'Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Vint Cerf', 'B', 1, 'EASY', 'General Knowledge', 1),
('What is the largest continent?', 'Africa', 'North America', 'Asia', 'Europe', 'C', 1, 'EASY', 'General Knowledge', 1),
('How many colors are in a rainbow?', '5', '6', '7', '8', 'C', 1, 'EASY', 'General Knowledge', 1),
('What does ATM stand for?', 'Automated Teller Machine', 'Automatic Transfer Machine', 'Automated Transfer Medium', 'Automatic Teller Medium', 'A', 1, 'EASY', 'General Knowledge', 1),

-- ENGLISH (10 questions)
('What is the synonym of "Happy"?', 'Sad', 'Joyful', 'Angry', 'Tired', 'B', 1, 'EASY', 'English', 1),
('What is the antonym of "Ancient"?', 'Old', 'Prehistoric', 'Modern', 'Antique', 'C', 1, 'EASY', 'English', 1),
('Which of the following is a noun?', 'Run', 'Beautiful', 'Happiness', 'Quickly', 'C', 1, 'EASY', 'English', 1),
('What is the past tense of "Go"?', 'Goed', 'Gone', 'Went', 'Going', 'C', 1, 'EASY', 'English', 1),
('Which sentence is grammatically correct?', 'She don\'t like apples.', 'She doesn\'t likes apples.', 'She doesn\'t like apples.', 'She not like apples.', 'C', 1, 'EASY', 'English', 1),
('What is a metaphor?', 'A direct comparison using like or as', 'An indirect comparison without using like or as', 'A type of rhyme', 'A figure of repetition', 'B', 2, 'MEDIUM', 'English', 1),
('What does the idiom "Break the ice" mean?', 'To break something made of ice', 'To start a conversation in a social situation', 'To cause damage', 'To cool something down', 'B', 1, 'EASY', 'English', 1),
('Which part of speech describes a verb?', 'Adjective', 'Adverb', 'Pronoun', 'Conjunction', 'B', 1, 'EASY', 'English', 1),
('What is the plural of "Criterion"?', 'Criterions', 'Criteria', 'Criterias', 'Criterium', 'B', 2, 'MEDIUM', 'English', 1),
('Choose the correctly spelled word:', 'Accomodate', 'Accommodate', 'Accommadate', 'Acomodate', 'B', 1, 'EASY', 'English', 1);
